# .github/workflows/publish.yml
name: Publish

on:
  push:
    tags:
      - v*  # e.g. v0.1.0
      - 'test_publish_*'

jobs:
  Publish:
    if: github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version-file: "pyproject.toml"

      - name: Build
        run: uv build

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/test_preflight.py

      - name: Smoke test (sdist)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/test_preflight.py

      - name: Publish
        run: uv publish
